apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    app: ads
  name: ads
spec:
  selector:
    matchLabels:
      app: ads
  serviceName: "ads"      
  template:
    metadata:
      labels:
        app: ads
    spec:
      containers:
      - image: hellof20/ads-dev:v0.8
        imagePullPolicy: IfNotPresent
        name: ads
        command: ["python", "main.py"]      
        ports:
        - containerPort: 8080
        resources:
          requests:
            memory: "256Mi"
            cpu: "256m"
          limits:
            memory: "256Mi"
            cpu: "256m"
        env:
          - name: host
            valueFrom:
              configMapKeyRef:
                name: mysql-config
                key: host
          - name: user
            valueFrom:
              configMapKeyRef:
                name: mysql-config
                key: user
          - name: password
            valueFrom:
              configMapKeyRef:
                name: mysql-config
                key: password
          - name: db
            valueFrom:
              configMapKeyRef:
                name: mysql-config
                key: db
        volumeMounts:
        - name: config
          mountPath: /app/client_secret.json
          subPath: client_secret.json
          readOnly: true
        - name: data
          mountPath: /data/pangu
      volumes:
      - name: config
        configMap:
          name: ads-dev-client-secret          
  volumeClaimTemplates:
  - metadata:
      name: data
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 10Gi

---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: ads
  name: ads
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: ads
  type: ClusterIP

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ads-ingress
spec:
  tls:
  - secretName: joey618-top
  rules:
  - http:
      paths:
      - path: /*
        pathType: ImplementationSpecific
        backend:
          service:
            name: ads
            port:
              number: 8080
