FROM python:3.7-alpine
ADD static /app/static
ADD templates /app/templates
ADD requirements.txt /app/
ADD main.py sql.py /app/
WORKDIR /app
RUN pip install -r requirements.txt
RUN apk add curl
RUN curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
RUN chmod +x kubectl
RUN mv kubectl /usr/local/bin/
CMD ["python", "main.py"]~