FROM python:3.7-alpine
RUN apk add terraform
RUN apk add mysql-client
RUN apk add mariadb-connector-c-dev
RUN apk add jq curl git
RUN apk add nodejs-current npm
RUN apk add --no-cache --upgrade bash
RUN curl -sSL https://sdk.cloud.google.com | bash
ENV PATH $PATH:/root/google-cloud-sdk/bin
ADD apply.sh destroy.sh /app/
WORKDIR /app