FROM python:3.7-alpine
RUN apk add terraform
RUN apk add mysql-client
RUN apk add mariadb-connector-c-dev
RUN apk add jq curl git
RUN apk add nodejs-current npm
RUN apk add --no-cache --upgrade bash
RUN curl -sSL https://sdk.cloud.google.com | bash
ENV PATH $PATH:/root/google-cloud-sdk/bin
RUN gcloud components install beta --quiet
RUN wget https://get.helm.sh/helm-v3.10.2-linux-amd64.tar.gz
RUN tar -zxvf helm-v3.10.2-linux-amd64.tar.gz
RUN mv linux-amd64/helm /usr/local/bin/helm
RUN gcloud components install kubectl
RUN gcloud components update
RUN apk add gettext libintl
ADD apply.sh destroy.sh /app/
WORKDIR /app
