FROM python:3.7-alpine
WORKDIR /app
RUN apk add curl gcc python3-dev libc-dev libffi-dev jq
RUN curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
RUN chmod +x kubectl
RUN mv kubectl /usr/local/bin/
ADD static /app/static
ADD templates /app/templates
ADD requirements.txt /app/
RUN pip install -r requirements.txt
ADD main.py sql.py /app/
CMD ["python", "main.py"]