FROM python:3.7-alpine
ADD static /app/static
ADD templates /app/templates
ADD requirements.txt /app/
ADD main.py sql.py /app/
WORKDIR /app
RUN pip install -r requirements.txt
CMD ["python", "main.py"]